sonar.projectKey=employee-management-cicd
sonar.projectName=Employee Management CI/CD
sonar.projectVersion=1.0

sonar.sources=application/app
sonar.tests=application/tests

sonar.python.version=3.12
sonar.sourceEncoding=UTF-8