pipeline {
    agent any

    environment {
        IMAGE_NAME = "employee-management-api"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies & Test') {
            steps {
                script {
                    docker.image('python:3.12-slim').inside {

                        dir('application') {

                            sh '''
                            python --version
                            pip install --upgrade pip
                            pip install -r requirements.txt

                            pytest
                            '''

                        }
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {

                sh """
                docker build -t ${IMAGE_NAME}:${IMAGE_TAG} application
                """

            }
        }

    }

    post {

        success {
            echo 'Pipeline Completed Successfully'
        }

        failure {
            echo 'Pipeline Failed'
        }

        always {
            cleanWs()
        }

    }

}